version: '3.4'

networks:
  main:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine          
    networks:
     - main
  userservice.api:
    image: ${DOCKER_REGISTRY-}userserviceapi
    build:
      context: .
      dockerfile: src/UserService.Api/Dockerfile
    depends_on:
     - rabbitmq
    networks:
     - main
  profileservice.api:
    image: ${DOCKER_REGISTRY-}profileserviceapi
    build:
      context: .
      dockerfile: src/ProfileService.Api/Dockerfile
    depends_on:
     - rabbitmq
    networks:
     - main

